#!/usr/bin/env php
<?php

require __DIR__ . '/autoload.php';

/**
 * Build Climate
 */
$climate = new League\CLImate\CLImate;

/**
 * Build Container
 */
$container = new League\Container\Container;
$container->delegate(new League\Container\ReflectionContainer);
$container->add(\Infra\Db::class, new \Infra\Db([
    'database_type' => getenv('DB_TYPE'),
    'database_name' => getenv('DB_BASE'),
    'server' => getenv('DB_HOST'),
    'username' => getenv('DB_USER'),
    'password' => getenv('DB_PASS'),
    'charset' => 'utf8'
]));

/**
 * Make console controller
 */
if ($argc >= 2) {
    $class = $argv[1];

    if (!class_exists($class)) {
        $climate->to('error')->red('Command not found.');
        exit;
    }

    $service = $container->get($class);

    if (!$service instanceof App\Contracts\Command) {
        $climate->to('warning')->yellow('This command is not a Command.');
        exit;
    }

    if ($service->handle()) {
        $climate->to('success')->green('This command has been executed');
        exit;
    }

    $climate->to('error')->red('Whoooops, there is something wrong.');
    exit;
}
